"""add chat metrics to messages

Revision ID: 2f998c6deeb7
Revises: 86ec60ab03b1
Create Date: 2026-07-23 14:35:34.944333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f998c6deeb7'
down_revision: Union[str, Sequence[str], None] = '86ec60ab03b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "messages",
        sa.Column("latency", sa.Float(), nullable=False, server_default="0"),
    )

    op.add_column(
        "messages",
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    op.add_column(
        "messages",
        sa.Column("completion_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    op.add_column(
        "messages",
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    op.add_column(
        "messages",
        sa.Column("estimated_cost", sa.Float(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'estimated_cost')
    op.drop_column('messages', 'total_tokens')
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    op.drop_column('messages', 'latency')
    # ### end Alembic commands ###
